services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: nest-distruibuidora
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./data/mysql:/var/lib/mysql